### ISSUE TITLE
timeseries_preprocessing.py: time offset

### ISSUE THREAD

**Issue by dyuliu** [HDI-Project/MLPrimitives#136]
https://github.com/HDI-Project/MLPrimitives/blob/e0032459a8fb54e230d118c97b3dcafaf00d5a6e/mlprimitives/custom/timeseries_preprocessing.py#L17

In this function:

X[start:end] is a window, as an input for prediction. 
y[end: end + target_size] is the prediction result.

When we are considering the anomaly start time, I think **index[end]** is more reasonable.

Current implementation takes index[start] as the anomaly occurring time, which leads to an offset for the found anomalous event.

**Comment by csala** [comment]
Hi @dyuliu,

Thanks for highlighting this. However, I'm not entirely sure about this being really needed: the `timeseries_preprocessing` primitive is just that, a preprocessing primitive, and is not necessarily related to anomaly detection.

So, since there are many scenarios where this primitive can be used, I would say that both X and y indexes might make sense in some cases.

My suggestion for this is to add a fourth output to the primitive, called `target_index`, which is exactly what you need: the indexes where `y` sequences start.
Would this solve your situation?

Meanwhile, an easy solution to come up with the right values is to simply add the constant value `window_length` to your indexes after you get the results from your pipeline.
