### ISSUE TITLE
Add DSP primitives

### ISSUE THREAD

**Issue by rjdiez** [HDI-Project/MLPrimitives#61]
I'd like to add primitives for Digital Signal Processing (DSP). These primitives will be used to detect anomalies in the telemetry data received from different satellites as part of project Orion, but they can be used to detect anomalies in any system.

Filename: dsp.py
Classname: freqAnalysis
Methods:
- fitFreqMax
- fitFreqStdDev
- produceFreqCompare
- produceBPF

There are some more methods used internally in the class: windowDesign, nextPowerOf2 

I also wrote the first JSON file: dsp.stdDevFreqAnalysis.json. This file points to the fitFreqStdDev method for data fitting and to the produceFreqCompare method for making predictions. Later I'll write more JSON files pointing to the other methods in the freqAnalysis class.

I also wrote two more classes for testing and scoring: 
Filename: dsp_utils.py
  Classname: SIGEN
    Methods: 
     - sigen
     - anomaliesGenerator
     - noiseGenerator
     - signalGenerator
     - show
  Classname: EVAL
    Methods:   
     - score
     - evaluate

**Comment by csala** [comment]
Thanks for this specification @rjdiez.
I need to make some suggestions and requests:

First of all, please make sure to follow the python coding standards when making the design. In this project, we follow the [PEP8](https://www.python.org/dev/peps/pep-0008/) recommendations, which are enforced by `flake8`, as well as the Google import order, enforced by `isort`. In general, even though we do not strictly enforce it, the [Google Python Style Guide](https://github.com/google/styleguide/blob/gh-pages/pyguide.md) is an excellent resource to keep in mind.

The most important things to consider are:
- Name the classes using `CamelCase` (first character in each word is Uppercase, including the first one)
- Name all the methods and variables using `snake_case` (all lowercase, words separated by underscore)

Then, in terms of MLPrimitives, bear in mind that:
- The methods called during the `fit` phase cannot return anything. Only the output from the method called during the `produce` phase does.
- If you are implementing this within mlprimitives module (which you are), it is recommended to name the `fit` and `produce` methods exactly that: `fit` and `produce` (instead of `fitFreqStdDev` and `produceFreqCompare`)
- The name of the JSON file has to be the Fully Qualified Name of the primitive class. So, it cannot be `dsp.stdDevFreqAnalysis.json`. It should be something like `mlprimitives.dsp.{class_name}.json`

Finally, I would like to have a clearer notion of what these methods do and how they are used.
Can you explain (in a sentence) what each one of them does and what inputs and outputs they have?

This is very important especially if they have to be combined in some way (output of one method to be used as part of the input for another one).

**Comment by rjdiez** [comment]
Hi @csala, thank you very much for the information on coding standards.

I have some questions regarding the names of the JSON files and methods:

> If you are implementing this within mlprimitives module (which you are), it is recommended to name the fit and produce methods exactly that: fit and produce (instead of fitFreqStdDev and produceFreqCompare)

I selected those names because I have several _fit_ and _produce_ methods in the same class. I don't want to put them in different classes because they are related, and I'd like to combine them in different ways via different JSON files. Additionally, the format of the JSON files supports that. Is it ok if I use snake_case but I keep the compound names?

> The name of the JSON file has to be the Fully Qualified Name of the primitive class. So, it cannot be dsp.stdDevFreqAnalysis.json. It should be something like mlprimitives.dsp.{class_name}.json
 
This will restrict the use of multiple methods in the same class. I thought that the idea was combining different _fit_ and _produce_ methods via different JSON files. If I use only the name of the class in the JSON filename, then it will be impossible to create two different JSON files pointing to different _fit_ and _produce_ methods in the same class. Additionally, I haven't seen the _mlprimitives_ as part of any JSON filename.

**Comment by csala** [comment]
> I selected those names because I have several _fit_ and _produce_ methods in the same class. I don't want to put them in different classes because they are related, and I'd like to combine them in different ways via different JSON files. Additionally, the format of the JSON files supports that. Is it ok if I use snake_case but I keep the compound names?

Absolutetly! Naming them exactly `fit` and `produce` is only a recommendation to make it easier to understand to new user, but what you explained is a perfect scenario to make an exception and use different names.

> > The name of the JSON file has to be the Fully Qualified Name of the primitive class. So, it cannot be dsp.stdDevFreqAnalysis.json. It should be something like mlprimitives.dsp.{class_name}.json
> 
> This will restrict the use of multiple methods in the same class. I thought that the idea was combining different _fit_ and _produce_ methods via different JSON files. If I use only the name of the class in the JSON filename, then it will be impossible to create two different JSON files pointing to different _fit_ and _produce_ methods in the same class.

That's right. But in this case I recommend you to use the FQN of the class, and then add a suffix that makes the distinction between the different use cases.
You can see an example of this in the `sklearn.ensemble.RandomForestClassifier` and `sklearn.ensemble.RandomForestClassifier_proba`.
Feel free to follow this schema, or to add an additional name after the class name, separated by a dot:
`mlprimitives.dsp.{class_name}.{some_other_identifier}.json`.

However, this arises some doubts:

1. How are the different methods related? Do they call each other, or are they independent, even if they are similar?
2. If they are independent but similar, perhaps using a parent class and then multiple subclasses would be better? You can see an example of this here: [mlprimitives/counters.py](https://github.com/HDI-Project/MLPrimitives/blob/master/mlprimitives/counters.py). You can see how there is a parent class `Counter` that has the common parts, and then each specific counter overrides the needed parts for each specific functionality.
3. If it does not make sense to make subclasses, perhaps it would make sense to make everything a single primitive (so a single JSON file), and control the different behaviors using a fixed hyperparameter? So, you would have a single class that has an `__init__` argument (e.g. `analysis_type`) which controls what type of analysis you want to perform. Then, this class would have a single `fit` and `predudce` couple of methods, which choose how to behave depending on the `analysis_type` value (maybe implement the different behaviors in separated methods, and have `fit` and `produce` call them accordingly.). You can see an example of this in the (mlprimitives.trivial.TrivialPredictor)[https://github.com/HDI-Project/MLPrimitives/blob/master/mlprimitives/trivial.py], where the `method` argument specifies which method will be called during `fit` to compute the `prediction` value.
You can see how this is specified as a fixed hyperparameter in the corresonding JSON file: (mlprimitives.trivial.TrivialPredictor.json)[https://github.com/HDI-Project/MLPrimitives/blob/master/mlblocks_primitives/mlprimitives.trivial.TrivialPredictor.json]

> Additionally, I haven't seen the _mlprimitives_ as part of any JSON filename.

That's because you didn't scroll down enough to find them :-)
All the examples that I showed you above have the `mlprimitives` bit in the JSON name.

**Comment by rjdiez** [comment]
1- _fit_ and _produce_ methods are independent.
2- they are not similar, but I'd like to combine them in different ways once I have more _fit_ and _produce_ methods. I'll keep in mind the organization in subclasses you proposed.
3- it could work, but... what's the idea of having the possibility of pointing to different _fit_ and _produce_ methods in the JSON file if we are trying to name them always the same way? We are trying to have JSON filenames with the class name embedded, so it's not a very good abstraction of the class, and we are trying to have _fit_ and _produce_ methods with the same name as they have in the class.... it sounds like we are restricting the flexibility provided by the JSON files. Anyway, I'll be back in Boston in two weeks, maybe we can talk more about this once I'm there. I'll name files in the way you proposed by now.
Thanks!

**Comment by csala** [comment]
> 3- it could work, but... what's the idea of having the possibility of pointing to different _fit_ and _produce_ methods in the JSON file if we are trying to name them always the same way? We are trying to have JSON filenames with the class name embedded, so it's not a very good abstraction of the class, and we are trying to have _fit_ and _produce_ methods with the same name as they have in the class.... it sounds like we are restricting the flexibility provided by the JSON files.

There are two levels here.

At the method name level, please bear in mind that there is a huge difference between integrating primitives that are already implemented in a third party library and implementing a new primitive from scratch, directly on _mlprimitives_.
So, the framework allows naming things differently mainly because this is what allows us to integrate things that have different names, but when we integrate things from scratch we try to chose the names sensibly to make the translation between JSON and Python as intuitive as possible.

But, of course, this thing about the naming is just a suggestion, and if having different names makes the code more readable and intuitive, please go for it! You will see that there are some of the examples implemented by us that have different names, like the counters that I showed you above that have `count` and `get_counts`, because `fit` and `produce` there would have been very confusing when looking at the python code.

At the file name level, there is a very strong argument here: Organization.
It's not about the abstraction. It's about answering this question: Once there are hundreds or even thousands of primitives in the repository, how will one know if a primitive has already been integrated if the name of the JSON can be different than the primitive? So, we enforce that the name of the primitive is part of the file name, even if you end up putting a suffix at the end, so we can see, at first sight, whether a primitive is already there or not.

And the last point is about having one or multiple classes, responding to your answer to point (1) above:
Knowing that the different methods are independent, I now see clear that the subclasses schema (which you already agreed on :-) is the one that makes more sense.
The main argument is making the abstraction simple: Since JSON primitives have only one behavior (one fit and one produce), making the corresponding classes also have one behavior is what makes it easier to go from one to the other.
At the end, there uses are required to look only at the JSON files, and they should be able to easily get the idea of that's going on under the hoods.

> Anyway, I'll be back in Boston in two weeks, maybe we can talk more about this once I'm there. I'll name files in the way you proposed by now.

Sounds good to me!

**Comment by rjdiez** [comment]
Hi @csala, 

Thanks for the explanation! it would be great if we can talk more in person. Are you in Boston? I'm already here.

I adjusted the style of the code following the PEP8 recommendations and some other recommendations from the Google Style Guide. 
I also added two new classes (filters and moments) and reorganized the code. There is only one fit and one produce method per class now. I'm planning to generate a pull request tomorrow. These are the names I'm planning to use:

Filename: dsp.py
  Classname: SpectralMask
  Classname: Filters (work in progress) 
  Classname: Moments (new)

Note: SpectralMask and Filters will probably inherit from SpectralAnalysis in the future.

JSON files:
   - mlprimitives.dsp.SpectralMask.json 
   - mlprimitives.dsp.filters.json 
   - mlprimitives.dsp.moments.json

Could you please tell me if these names are ok?

**Comment by csala** [comment]
Yes! It sounds much better now! :-)

The only think that I would mention, is that the filenames should match the classname case (so `Filters.json` instead of `filters.json`, etc.), but all the rest sounds right on spot.

Also, we are about to merge a new PR, #77, that changes a little bit the structure of the repository.
Please keep an eye on that, and if this reaches master before you make your PR, please merge those changes into your branch before making yours, otherwise it won't be possible to merge it without conflicts.

What these changes imply for you is only that your primitives module will have to be `mlprimitives.candidates.dsp` instead of `mlprimitives.dsp` and the JSON files will need to be named accordingly, but the rest will be exactly the same.
